name: Sync Multiple Public Repos

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repositories list
        env:
          REPO_URLS: |
            https://github.com/pallasite99/rental-reminder
          MY_REPO_URLS: |
            https://github.com/akashgaikwad26/CloneRepo
        run: echo "Repositories list set up."

      - name: Clone and Sync Repositories
        env:
          REPO_URLS: ${{ toJSON(env.REPO_URLS) }}
          MY_REPO_URLS: ${{ toJSON(env.MY_REPO_URLS) }}
        run: |
          # Convert JSON arrays into bash arrays
          repo_urls=($(echo "$REPO_URLS" | jq -r '.[]'))
          my_repo_urls=($(echo "$MY_REPO_URLS" | jq -r '.[]'))

          # Loop through each pair of repositories
          for i in "${!repo_urls[@]}"; do
            public_repo_url="${repo_urls[$i]}"
            my_repo_url="${my_repo_urls[$i]}"

            # Use the token for authentication
            auth_public_repo_url="${public_repo_url/https:\/\//https:\/\/${{ secrets.GITHUB_TOKEN }}@}"
            auth_my_repo_url="${my_repo_url/https:\/\//https:\/\/${{ secrets.GITHUB_TOKEN }}@}"

            echo "Syncing $public_repo_url to $my_repo_url"

            # Clone the public repo as a mirror
            if git clone --mirror "$auth_public_repo_url" temp_repo.git; then
              cd temp_repo.git
              
              # Add and push to the private repo
              git remote add my-repo "$auth_my_repo_url"
              git fetch origin
              git push --mirror my-repo || echo "Warning: Push to $my_repo_url failed."
              
              cd ..
              rm -rf temp_repo.git
            else
              echo "Error: Cloning $public_repo_url failed, skipping."
            fi
          done
