name: Sync Single Public Repo

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Clone and Sync Repository
        run: |
          # Define the source (public) and target (public) repositories directly in the script
          public_repo_url="https://github.com/pallasite99/rental-reminder"
          target_repo_url="https://github.com/akashgaikwad26/CloneRepo"

          echo "Syncing $public_repo_url to $target_repo_url"

          # Clone the public repo as a mirror
          if git clone --mirror "$public_repo_url" temp_repo.git; then
            cd temp_repo.git
            
            # Add and push to the target repo (no authentication needed for public repos)
            git remote add target "$target_repo_url"
            git fetch origin
            git push --mirror target || echo "Warning: Push to $target_repo_url failed."
            
            cd ..
            rm -rf temp_repo.git
          else
            echo "Error: Cloning $public_repo_url failed, skipping."
          fi
