name: Sync Single Public Repo

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Target Repository
        uses: actions/checkout@v2
        with:
          repository: "akashgaikwad26/CloneRepo"  # Target repository
          token: "${{ secrets.GITHUB_TOKEN }}"
          path: "target_repo"  # Clone into a specific directory

      - name: Clone and Sync Public Repository
        run: |
          # Define the public repository URL
          public_repo_url="https://github.com/pallasite99/rental-reminder"
          
          echo "Syncing $public_repo_url to target_repo"

          # Clone the public repo as a mirror
          if git clone --mirror "$public_repo_url" temp_repo.git; then
            cd temp_repo.git
            
            # Add the target repo (cloned into target_repo) as a remote
            git remote add target ../target_repo
            git fetch origin
            git push --mirror target || echo "Warning: Push to target_repo failed."
            
            cd ..
            rm -rf temp_repo.git
          else
            echo "Error: Cloning $public_repo_url failed, skipping."
          fi
