name: Sync Multiple Public Repos

on:
  schedule:
    - cron: '0 * * * *'  
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repositories list
        id: repos
        run: |
          echo "REPO_URLS=https://github.com/pallasite99/rental-reminder" >> $GITHUB_ENV
          echo "MY_REPO_URLS=https://github.com/akashgaikwad26/CloneRepo" >> $GITHUB_ENV

      - name: Clone and Sync Repositories
        run: |
          repo_urls=($REPO_URLS)
          my_repo_urls=($MY_REPO_URLS)

          for i in "${!repo_urls[@]}"; do
            public_repo_url="${repo_urls[$i]}"
            my_repo_url="${my_repo_urls[$i]}"

       
            git clone --mirror "$public_repo_url" temp_repo.git

            cd temp_repo.git
            git remote add my-repo "$my_repo_url"
            git fetch origin
            git push --mirror my-repo

            cd ..
            rm -rf temp_repo.git
          done
