name: Sync Multiple Public Repos

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repositories list
        env:
          REPO_URLS: '["https://github.com/pallasite99/rental-reminder"]'
          MY_REPO_URLS: '["https://github.com/akashgaikwad26/CloneRepo"]'
        run: echo "Repositories list set up."

      - name: Clone and Sync Repositories
        run: |
          # Print the environment variables for debugging
          echo "REPO_URLS: $REPO_URLS"
          echo "MY_REPO_URLS: $MY_REPO_URLS"

          # Convert JSON arrays into bash arrays, only if they are non-empty
          if [ -n "$REPO_URLS" ] && [ -n "$MY_REPO_URLS" ]; then
            # Convert the JSON arrays into bash arrays using jq
            repo_urls=($(echo "$REPO_URLS" | jq -r '.[]'))
            my_repo_urls=($(echo "$MY_REPO_URLS" | jq -r '.[]'))

            echo "Repositories to sync: ${repo_urls[@]}"
            echo "Target repositories: ${my_repo_urls[@]}"

            # Loop through each pair of repositories
            for i in "${!repo_urls[@]}"; do
              public_repo_url="${repo_urls[$i]}"
              my_repo_url="${my_repo_urls[$i]}"

              echo "Syncing $public_repo_url to $my_repo_url"

              # Add your sync logic here...

            done
          else
            echo "Error: REPO_URLS or MY_REPO_URLS is not set correctly."
          fi
